
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'SeasoningManagemer'
project './SeasoningManager/SeasoningManager'
project './SeasoningManagerCommon/SeasoningManagerCommon'
platform :ios, '13.0'

def shared_pod
    pod 'RxSwift' , '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxDataSources', '~> 4'
    pod 'RxGesture', '~> 3'
end

def test_shared_pod
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
end


target 'SeasoningManager' do
  use_frameworks!
  project './SeasoningManager/SeasoningManager'

  pod 'LicensePlist'
  shared_pod
  
  target 'SeasoningManagerTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pod
  end

end

target 'SeasoningManagerCommon' do
  use_frameworks!
  shared_pod
  project './SeasoningManagerCommon/SeasoningManagerCommon'
end
